eptos/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from registration.views import register

admin.autodiscover()
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse_lazy
from commons.views import CreateAuctionView, AuctionListView, auction_detail, place_bid, UserDetailView, AccountProfileView

urlpatterns = patterns(
    '',
    url(r'^accounts/register/$',
        register,
        {
            'backend': 'registration.backends.simple.SimpleBackend',
            'success_url': reverse_lazy('commons.views.home')
        },
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

    url(r'^$', 'commons.views.home', name='home'),
    url(r'^login/$', login),
    url(r'^logout/$',
        logout, {'next_page': reverse_lazy('commons.views.home')},
        name='logout'),

    url(r'^auctions/(?P<auction_id>\d+)/$',
        auction_detail,
        name='auction_detail'),
    url(r'^auctions/(?P<auction_id>\d+)/place_bid$',
        place_bid,
        name='place_bid'),
    url(r'^auctions/create/$',
        login_required(CreateAuctionView.as_view()),
        name='create_auction'),
    url(r'^auctions/$', AuctionListView.as_view(),
        name='auctions_list'),
    url(r'^accounts/profile/$',
        AccountProfileView.as_view(),
        name='user_profile'),
    url(r'^users/(?P<pk>\d+)/$',
        UserDetailView.as_view(),
        name='user_detail'),
    url(r'^admin/', include(admin.site.urls)),
)

commons/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template import Context
from django.template.loader import get_template
from django.utils.safestring import mark_safe


class Auction(models.Model):
    user = models.ForeignKey(User)
    creation_date = models.DateField(auto_now_add=True)
    address = models.CharField(max_length=255, verbose_name='Where is it?')
    name = models.CharField(
        max_length=255,
        verbose_name='Pick an original name for your offering')

    AUCTION_TYPE_CHOICES = (
        ('A', 'Apartment'),
        ('H', 'House'),
        ('R', 'Room'))
    auction_type = models.CharField(
        max_length=255,
        verbose_name='What type of place is it?',
        choices=AUCTION_TYPE_CHOICES
    )
    minimum_bid = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name='How much are you asking for?')

    def list_display(self):
        t = get_template('auctions/list_display.html')
        c = Context({'auction': self})
        return mark_safe(t.render(c))

    def last_bid(self):
        if not self.bid_set or not self.bid_set.count():
            return None

        return self.bid_set.order_by('id').reverse()[0]

    def pretty_auction_type(self):
        return dict(Auction.AUCTION_TYPE_CHOICES)[self.auction_type]

    def pretty_minimum_bid(self):
        return u'US$ {0}'.format(self.minimum_bid)

    def pretty_last_bid(self):
        if not self.bid_set or not self.bid_set.count():
            return self.pretty_minimum_bid()

        return u'US$ {0}'.format(self.bid_set.order_by('id').reverse()[0].value)


class Bid(models.Model):
    user = models.ForeignKey(User)
    auction = models.ForeignKey(Auction)
    creation_date = models.DateField(auto_now_add=True)
    value = models.DecimalField(max_digits=7, decimal_places=2)

    def __unicode__(self):
        return u'{0} - {1}'.format(self.creation_date, self.value)

    def pretty_value(self):
        return u'US$ {0}'.format(self.value)

commons/forms.py
from django import forms
from commons.models import Auction, Bid


class PlaceBidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['value']


class DetailAuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['name', 'address', 'auction_type', 'minimum_bid']


class CreateAuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['name', 'address', 'auction_type', 'minimum_bid']

commons/views.py
# -*- coding: utf-8 -*-

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic import FormView, ListView
from django.views.generic import DetailView, TemplateView
from django.template import RequestContext
from commons.forms import CreateAuctionForm, PlaceBidForm
from commons.models import Auction


def home(request):

    auctions = Auction.objects.all()

    return render_to_response(
        'home.html',
        {
            'auctions': auctions
        },
        context_instance=RequestContext(request))


def auction_detail(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)

    return render_to_response('auction_detail.html',
                              {
                                  'auction': auction,
                                  'bid_form': PlaceBidForm()
                              },
                              context_instance=RequestContext(request))


@login_required
def place_bid(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)

    if request.method == 'POST':

        form = PlaceBidForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.instance.auction = auction
            form.save()

            request.flash['success'] = u'Bid placed successfully for %s!' % form.instance.value
        else:
            return render_to_response('auction_detail.html',
                                      {
                                          'auction': auction,
                                          'bid_form': form
                                      },
                                      context_instance=RequestContext(request))

    return HttpResponseRedirect(reverse_lazy(auction_detail, args=(auction.id,)))


class AuctionDetailView(DetailView):
    model = Auction
    template_name = 'auction_detail.html'


class CreateAuctionView(FormView):
    template_name = 'auction_create.html'
    form_class = CreateAuctionForm

    def form_valid(self, form):
        auction = form.instance
        auction.user = self.request.user
        auction.save()

        self.request.flash['success'] = 'Auction created successfully!'

        return HttpResponseRedirect(
            reverse_lazy('auction_detail', args=(auction.id,)))


class AuctionListView(ListView):
    model = Auction
    template_name = 'auction_list.html'


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'detail_user'


class AccountProfileView(TemplateView):
    template_name = 'account_profile.html'

    def get_context_data(self, **kwargs):
        context = super(AccountProfileView, self).get_context_data(**kwargs)

        context['user'] = self.request.user

        return context

commons/templates/account_profile.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}
{% load url from future %}

{% block content %}
    <div class="container">
        <h1>Account profile</h1>
        <hr />

        <h2>Open auctions</h2>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Auction</th>
                <th>Creation date</th>
                <th>Minimum bid</th>
            </tr>
            </thead>
            {% for auction in user.auction_set.all %}
                <tr>
                    <td><a href="{% url 'auction_detail' auction.id %}">{{ auction.name }}</a></td>
                    <td>{{ auction.creation_date }}</td>
                    <td>{{ auction.pretty_minimum_bid }}</td>
                </tr>
            {% endfor %}
        </table>

        <h2>Open bids</h2>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Auction</th>
                <th>Bid amount</th>
            </tr>
            </thead>
            {% for bid in user.bid_set.all %}
                <tr>
                    <td><a href="{% url 'auction_detail' bid.auction.id %}">{{ bid.auction.name }}</a></td>
                    <td>{{ bid.pretty_value }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

commons/templates/auction_create.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}

{% block content %}
    <h1>Create auction</h1>

    <hr />

    <form method="post" action=".">
        {% csrf_token %}
        {{ form|as_bootstrap }}

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Create your auction!</button>
        </div>
    </form>
{% endblock %}

commons/templates/auction_detail.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}
{% load static %}
{% load url from future %}

{% block content %}

    <div class="row">
        <div class="span12">
            <h1>{{ auction.name }}</h1>
        </div>
    </div>

    <div class="row">
        <div class="span2">
            <img src="{% static 'img/stock_room.png' %}" />
        </div>
        <div class="span6">
            {{ auction.pretty_auction_type }}
            <address>{{ auction.address }}</address>
        </div>
        <div class="span4 pull-right">
            <label>Minimum Bid:</label>
            <span class="price">US$ {{ auction.minimum_bid }}</span>
            <label>Current Bid:</label>
            <span class="price">{{ auction.pretty_last_bid }}</span>
            {% if auction.last_bid %}
                <a href="{% url 'user_detail' auction.last_bid.user.id %}">from {{ auction.last_bid.user.username }}</a>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="span2"></div>
        <div class="span10">
            <form class="form-inline add_bid" method="post" action="{% url 'commons.views.place_bid' auction.id %}">
                {% csrf_token %}

                {{ bid_form|as_bootstrap }}
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Place Bid!</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

commons/templates/auction_list.html
{% extends 'base.html' %}

{% load bootstrap_toolkit %}

{% block content %}
    <h1>Auction list</h1>

    <hr />

    {% for auction in auction_list %}
        {{ auction.list_display }}
    {% endfor %}
{% endblock %}

commons/templates/auctions/list_display.html
{% load static %}
{% load url from future %}

<div class="row auction_list_display">
    <div class="span2">
        <img src="{% static 'img/stock_room.png' %}" />
    </div>
    <div class="span6">
        <h3><a href="{% url 'auction_detail' auction.id %}">{{ auction.name }}</a></h3>
        {{ auction.pretty_auction_type }}
        <address>{{ auction.address }}</address>
        <strong>Offered by:</strong> <a href="{% url 'user_detail' auction.user.id %}">{{ auction.user.username }}</a>
    </div>
    <div class="span2 pull-right">
        <span class="price">{{ auction.pretty_last_bid }}</span>
        <br />
        <a href="{% url 'auction_detail' auction.id %}" class="btn btn-success apply_button">Apply!</a>
    </div>
</div>

commons/templates/base.html
{% load static %}
{% load url from future %}

<!DOCTYPE html>
<html>
<head>
    <title>BidHome</title>    <!-- Bootstrap -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/styles.css" %}" rel="stylesheet" media="screen">
    <script src="{% static "js/jquery-1.9.1.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">BidHome</a>
            <div class="nav-collapse collapse">
                <ul class="nav pull-right right">
                    <li class="btn-inverse">
                        <a href="{% url 'create_auction' %}">
                            <i class="icon-plus icon-white"></i>
                            Create an auction!
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'user_profile' %}">
                                <span>{{ user.username }}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">
                                <span>logout</span>
                            </a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'django.contrib.auth.views.login' %}?next=/">login</a></li>
                        <li><a href="{% url 'registration.views.register' %}">or sign up</a></li>
                    {% endif %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'img/flag_uk.png' %}" /> English <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><img src="{% static 'img/flag_chile.png' %}" /> Spanish</a></li>
                            <li><a href="#"><img src="{% static 'img/flag_portugal.png' %}" /> Portuguese</a></li>
                            <li><a href="#"><img src="{% static 'img/flag_uk.png' %}" /> English</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="{% url 'auctions_list' %}">Places</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">

    {% if request.flash.success %}
        <div class="alert alert-success">
            {{ request.flash.success }}
        </div>
    {% endif %}


    {% if request.flash.error %}
        <div class="alert alert-error">
            {{ request.flash.error }}
        </div>
    {% endif %}

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

commons/templates/home.html
{% load url from future%}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>BidHome</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta name="google-site-verification" content="Ri6_cLq0lEi20PBbHKWT7xK0o3fNYAbaU-Rqn1abmbw" />

    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/styles.css" %}" rel="stylesheet" media="screen">
    <script src="{% static "js/jquery-1.9.1.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <style type="text/css">
        html {
            height: 100%
        }
        body {
            height: 100%; margin: 0; padding: 0
        }
        #map-canvas { height: 100% }

        .imgContent {
            width: 150px;
            padding-right: 20px;
            float: left;
        }

        .bodyContent {
            width: 300px;
            float: left;
        }

        .bodyContent h3 {
            margin: 0px 0px;
        }

        #map-canvas img {
            max-width: none;
        }

        #map-canvas label { width: auto; display:inline; }
        #map-canvas img { max-width: none; }
    </style>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjeEi63VJhxfGjuIrf6SEEc73LPYJx99o&sensor=true">
    </script>
    <script type="text/javascript">
        var app =  new function () {
            var myOptions = {
                center: new google.maps.LatLng(-34.397, 150.644),
                zoom: 14,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                mapTypeControl: false,
                zoomControl: true,
                panControl : false,
                rotateControl : false,
                scaleControl : false,
                overviewMapControl : false
            };
            var me = this;
            var appMap;
            var appGeocoder;
            var currentPosition;
            var markers;
            var socket;

            return {
                init : function() {
                    var that = this;
                    this.updateCurrentPosition();

                    me.appGeocoder = new google.maps.Geocoder();
                    me.appMap = new google.maps.Map(document.getElementById("map-canvas"),myOptions);
                },

                updateCurrentPosition : function() {
                    if (navigator.geolocation) {
                        var that = this;

                        navigator.geolocation.getCurrentPosition(function( position ){
                                    // Log that this is the initial position.
                                    console.log( "Position Found" );
                                    var calculatedPosition = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                                    if (me.currentPosition === undefined) {
                                        me.appMap.setCenter(calculatedPosition);
                                    }

                                    me.currentPosition = calculatedPosition;

                                    that.getAuctions();
                                },
                                function( error ){
                                    console.log( "Something went wrong: ", error );
                                    me.currentPosition =   new google.maps.LatLng(-34.397, 150.644);
                                },
                                {
                                    maximumAge:Infinity,
                                    enableHighAccuracy: true
                                } );
                    } else {
                        alert('I guess this browser does not support geolocation!');
                    }
                },

                getAuctions: function() {
                    var that = this;

                    {% for auction in auctions %}
                        me.appGeocoder.geocode( { 'address': '{{ auction.address }}'}, function(results, status) {
                            if (status == google.maps.GeocoderStatus.OK) {
                                that.displayAuction({
                                    id : {{ auction.id }},
                                    loc : [results[0].geometry.location.kb, results[0].geometry.location.lb],
                                    name: '{{ auction.name }}',
                                    address: '{{ auction.address }}',
                                    currentBid: '{{ auction.pretty_last_bid }}'
                                });
                            } else {
                                console.log("Geocode was not successful for the following reason: " + status);
                            }
                        });
                    {% endfor %}
                },

                displayAuction: function(auction) {
                    var that = this;
                    var auctionMarker = new google.maps.Marker({
                        position: new google.maps.LatLng(auction.loc[0], auction.loc[1]),
                        map: me.appMap,
                        animation: google.maps.Animation.DROP,
                        title : auction.name
                    });

                    that.complementAuction(auctionMarker, auction);

                    return auctionMarker;
                },

                complementAuction: function (auctionMarker, auction) {
                    var that = this;
                    var img = '<a href="/auctions/' + auction.id + '" target="_blank"><img src="{% static "img/stock_room.png" %}"></a>';
                    var contentString =
                            '<div class="content">' +
                                    '   <div class="imgContent">' + img + '</div>' +
                                    '   <div class="bodyContent">' +
                                    '       <h3>' + auction.name + '</h3>' +
                                    '       <address>' + auction.address + '</address>' +
                                    '       <a class="btn btn-success" href="/auctions/' + auction.id + '">Bid for this place!</a>' +
                                    '       <span class="price">' + auction.currentBid + '</span>' +
                                    '   </div>' +
                                    '</div>';

                    var infowindow = new google.maps.InfoWindow({content:contentString});

                    google.maps.event.addListener(auctionMarker, 'click', function () {
                        infowindow.open(me.appMap, auctionMarker);
                    });

                }
            }
        }
    </script>
</head>
<body onload="app.init()">
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">BidHome</a>
            <div class="nav-collapse collapse">
                <ul class="nav pull-right right">
                    <li class="btn-inverse">
                        <a href="{% url 'create_auction' %}">
                            <i class="icon-plus icon-white"></i>
                            Create an auction!
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'user_profile' %}">
                                <span>{{ user.username }}</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">
                                <span>logout</span>
                            </a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'django.contrib.auth.views.login' %}?next=/">login</a></li>
                        <li><a href="{% url 'registration.views.register' %}">or sign up</a></li>
                    {% endif %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'img/flag_uk.png' %}" /> English <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><img src="{% static 'img/flag_chile.png' %}" /> Spanish</a></li>
                            <li><a href="#"><img src="{% static 'img/flag_portugal.png' %}" /> Portuguese</a></li>
                            <li><a href="#"><img src="{% static 'img/flag_uk.png' %}" /> English</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav">
                    <li class="active"><a href="{% url 'auctions_list' %}">Places</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="map-canvas"/>

<script>

</script>
</body>
</html>

commons/templates/user_detail.html
{% extends 'base.html' %}

{% load url from future %}

{% block content %}
    <h1>{{ detail_user.username }}</h1>

    <hr />

    <h2>Open auctions</h2>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Auction</th>
                <th>Creation date</th>
                <th>Minimum bid</th>
            </tr>
        </thead>
        {% for auction in detail_user.auction_set.all %}
            <tr>
                <td><a href="{% url 'auction_detail' auction.id %}">{{ auction.name }}</a></td>
                <td>{{ auction.creation_date }}</td>
                <td>{{ auction.pretty_minimum_bid }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}